image: node:latest

stages:
  - npm_build
  - upload_file

BuildFiles:
  stage: npm_build
  script:
   - cp .env.production .env
   - npm install -g cnpm --registry=https://registry.npm.taobao.org
   - cnpm install
   - cnpm run build
   - tar -zcvf files.tar.gz dist
  artifacts:
    paths:
     - files.tar.gz
     - dist/
  cache:
    key: node_modules
    paths:
    - node_modules/

UploadFile:
  stage: upload_file
  before_script:
   - sed "s/deb.debian.org/mirrors.nju.edu.cn/g" /etc/apt/sources.list -i && sed "s/security.debian.org/mirrors.nju.edu.cn/g" /etc/apt/sources.list -i
   - apt update && apt upgrade -y
   - 'which scp || apt install ssh -y'
   - echo "$SSH_PRIVATE_KEY" > deploy.key
   - chmod 0600 deploy.key
   - '[ -f  ~/.ssh/known_hosts ] && rm ~/.ssh/known_hosts'
  script:
   - scp -r -o StrictHostKeyChecking=no -i deploy.key dist "$DEPLOY_SERVER":~/front
   - rm deploy.key
  cache: {}
  only:
   - master
  dependencies:
   - BuildFiles

UploadFileTest:
  stage: upload_file
  before_script:
   - sed "s/deb.debian.org/mirrors.nju.edu.cn/g" /etc/apt/sources.list -i && sed "s/security.debian.org/mirrors.nju.edu.cn/g" /etc/apt/sources.list -i
   - apt update && apt upgrade -y
   - 'which scp || apt install ssh -y'
   - echo "$SSH_PRIVATE_KEY" > deploy.key
   - chmod 0600 deploy.key
   - '[ -f  ~/.ssh/known_hosts ] && rm ~/.ssh/known_hosts'
  script:
   - scp -r -o StrictHostKeyChecking=no -i deploy.key dist "$TEST_SERVER":~/front
   - rm deploy.key
  cache: {}
  except:
   - master
   - dwxh
  when: manual
  dependencies:
   - BuildFiles

UploadFileDWXH:
  stage: upload_file
  before_script:
   - sed "s/deb.debian.org/mirrors.nju.edu.cn/g" /etc/apt/sources.list -i && sed "s/security.debian.org/mirrors.nju.edu.cn/g" /etc/apt/sources.list -i
   - apt update && apt upgrade -y
   - 'which scp || apt install ssh -y'
   - echo "$SSH_PRIVATE_KEY" > deploy.key
   - chmod 0600 deploy.key
   - '[ -f  ~/.ssh/known_hosts ] && rm ~/.ssh/known_hosts'
  script:
   - scp -r -o StrictHostKeyChecking=no -i deploy.key dist "$TEST_SERVER":~/front
   - rm deploy.key
  cache: {}
  only:
   - dwxh
  dependencies:
   - BuildFiles
